version: "3.4"
services:
  https-portal.dnp.dappnode.eth:
    build: .
    image: "https-portal.dnp.dappnode.eth:0.1.0"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      STAGE: dappnode-api
      CERTAPI_URL: "ns.dappnode.io:5000"
      PUBLIC_DOMAIN: null
      NAME: https-portal.dnp.dappnode.eth
    volumes:
      - "portal-certs:/var/lib/https-portal/"
      - "portal-data:/var/run/domains.d/"
volumes:
  portal-certs: {}
  portal-data: {}
