version: '3.8'

services:
  https-portal:
    build: .
    ports:
      - '80:80'
      - '443:443'
    environment: 
      STAGE: 'dappnode-api'
      DAPPMANAGER_URL: 127.0.0.1
      CERTAPI_URL: 127.0.0.1
    volumes:
       - "portal-certs:/var/lib/https-portal/wildcard_certs/"
       - type: bind
         source: ${pwd}/domains.txt
         target: /var/run/domains
networks: 
  default:
    external: 
      name: dappnode_public