version: '3.8'

services:
  https-portal:
    build: .
    container_name: DAppNodePackage-https-portal.dnp.dappnode.eth
    ports:
      - '80:80'
      - '443:443'
    environment: 
      STAGE: 'dappnode-api'
      CERTAPI_URL: 'ns.dappnode.io:5000'
      PUBLIC_DOMAIN: 
    volumes:
      - "portal-certs:/var/lib/https-portal/"
      - "portal-data:/var/run/domains.d/"
    networks: 
      - dncore_network
      - dappnode_public
       
networks: 
  dappnode_public:
    external: true
  dncore_network:
    external: true

volumes: 
  portal-certs:
  portal-data:
