name: "Main"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  unit-test:
    defaults:
      run:
        working-directory: /api
    runs-on: ubuntu-16.04
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - run: yarn build
      - run: yarn lint

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
